name: build-dist

on:
  pull_request:
    branches:
      - main

jobs:
  build-dist:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install
        run: npm ci
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'dist/**/*'
          commit_message: 'chore: build dist'
